import { BranchDefinition } from "../types/workflow";

/**
 * Standard Branch Structure for the Unified Workflow Model.
 * Every workflow generated by the system will follow this logical sequence.
 */
export const STANDARD_BRANCHES: BranchDefinition[] = [
    {
        id: 'initial',
        name: 'Initial Steps',
        type: 'GENERAL',
        allowedBlockTypes: [
            'ORDER_CREATED',
            'ITEMS_TO_SHOOT',
            'SST',
            'WAIT_PAYMENT',
            'SEND_NOTIFICATION',
            'IF_ELSE',
            'PRO_ASSIGNING',
            'RETOUCHER_ASSIGNING',
            'PHOTO_SHOOT',
            'VIDEO_SHOOT',
            'PHOTO_RETOUCHING',
            'VIDEO_RETOUCHING',
            'MATCHING',
            'FILE_RENAMING',
            'MODERATION',
            'EXTERNAL_PROCESS',
            'SEND_TO_CLIENT'
        ]
    },
    {
        id: 'photo',
        name: '📸 Photo Branch',
        type: 'PHOTO',
        allowedBlockTypes: [
            'PRO_ASSIGNING',
            'PHOTO_SHOOT',
            'SST',
            'MATCHING',
            'RETOUCHER_ASSIGNING',
            'PHOTO_RETOUCHING',
            'FILE_RENAMING',
            'MODERATION',
            'EXTERNAL_PROCESS',
            'IF_ELSE',
            'SEND_TO_CLIENT'
        ]
    },
    {
        id: 'video',
        name: '🎬 Video Branch',
        type: 'VIDEO',
        allowedBlockTypes: [
            'PRO_ASSIGNING',
            'VIDEO_SHOOT',
            'RETOUCHER_ASSIGNING',
            'VIDEO_RETOUCHING',
            'FILE_RENAMING',
            'MODERATION',
            'EXTERNAL_PROCESS',
            'IF_ELSE',
            'SEND_TO_CLIENT'
        ]
    },
    {
        id: 'completion',
        name: 'Completion',
        type: 'GENERAL',
        allowedBlockTypes: [
            'MERGE',
            'SEND_NOTIFICATION',
            'FILE_STORAGE',
            'SEND_TO_CLIENT',
            'MODERATION',
            'FILE_RENAMING',
            'EXTERNAL_PROCESS'
        ]
    }
];
